name: .NET CI/CD

on:
  push:
    branches: [ "master" ]  # Triggers on push to master

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Runs on a GitHub-hosted Windows VM

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish Application
      run: dotnet publish -c Release -o ./published

    - name: Upload Artifact (Published App)
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./published

    - name: Deploy to Local Machine
      run: |
        mkdir "D:\RazorToDoPub\MyApp" -Force
        robocopy ".\published" "D:\RazorToDoPub\MyApp" /E /IS /IT /NFL /NDL /NP
        if ($LASTEXITCODE -gt 1) { exit 1 }
