name: Deploy .NET App

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Running on your local machine

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore --configuration Release

    - name: Publish Project
      run: dotnet publish -c Release -o published

    # Stop IIS App Pool before copying files (to avoid file locking issue)
    - name: Stop IIS App Pool
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "RazorTodoPool"
      shell: powershell

    - name: Deploy to Local Folder
      run: |
        mkdir "D:\RazorToDoPub\MyApp" -Force
        robocopy ".\published" "D:\RazorToDoPub\MyApp" /E /XO /IT
      shell: powershell

    # Restart IIS App Pool after deployment
    - name: Start IIS App Pool
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "RazorTodoPool"
      shell: powershell
