name: Deploy .NET App

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore --configuration Release

    - name: Publish Project
      run: |
        dotnet publish -c Release -o "$env:USERPROFILE\published" --verbosity detailed
      shell: powershell

    - name: Stop IIS App Pool
      run: |
        Import-Module WebAdministration
        $appPoolName = "RazorTodoPool"
        $appPoolStatus = (Get-WebAppPoolState -Name $appPoolName).Value
        if ($appPoolStatus -ne "Stopped") {
          Stop-WebAppPool -Name $appPoolName
          Start-Sleep -s 5
        } else {
          Write-Host "App Pool is already stopped."
        }
      shell: powershell

    - name: Deploy to Local Folder
      run: |
        mkdir "D:\RazorToDoPub\MyApp" -Force
        robocopy "$env:USERPROFILE\published" "D:\RazorToDoPub\MyApp" /E /XO /IT
        if ($LASTEXITCODE -gt 3) { exit 1 }
      shell: powershell

    - name: Start IIS App Pool
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "RazorTodoPool"
      shell: powershell
